version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organ_donation_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/organ_donation
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - organ_network

  db:
    image: postgres:15-alpine
    container_name: organ_donation_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: organ_donation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - organ_network

  redis:
    image: redis:7-alpine
    container_name: organ_donation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - organ_network

volumes:
  postgres_data:
  redis_data:


networks:
  organ_network:
    driver: bridge
